version: '3'

services:

  managed-node-a:
    image: python:buster
    container_name: ansible-managed-a
    tty: true 

  managed-node-b:
    image: python:buster
    container_name: ansible-managed-b
    tty: true 

  control-node:
    image: ansible
    container_name: ansible-control
    tty: true
    volumes:
      - ./tutorial:/tutorial
