version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
jobs:
  build-and-push-managednode-to-gcr:
    description: Build and push the managed node image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build_and_push_image:
          dockerfile: managednode.Dockerfile
          path: docker
          image: hsbc-proj-1/managednode
          registry-url: eu.gcr.io
    
  update-managed-node-in-ansible-play-live-deployment:
    description: Deploy new managednode container to existing deployment on Google Kubernetes Engine
    machine: true
    steps:
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/publish-and-rollout-image:
          cluster: hsbc-cluster-1
          container: managednode
          deployment: ansible-play-deployment
          image: eu.gcr.io/hsbc-proj-1/managednode:latest
          tag: $CIRCLE_SHA1

workflows:
  build_update_deploy:
    jobs:
      - build-and-push-managednode-to-gcr
      - update-managed-node-in-ansible-play-live-deployment:
          requires:
            - build-and-push-managednode-to-gcr