version: '3'

services:

  managednode:
    image: managednode

  controlnode:
    image: controlnode
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      
    # Mount the tutorial as a volume at runtime to get dynamic update
    # during tutorial development.
    volumes:
      - ./tutorial:/tutorial
