version: '3'

services:

  managednode:
    image: managednode

  controlnode:
    image: controlnode
    # Mount the tutorial as a volume at runtime to get dynamic update
    # during tutorial development.
    volumes:
      - ./tutorial:/tutorial
