version: '3.2' # Must be point-2 not just 3 for the bind mount to work.

services:

  managednode:
    image: managednode

  controlnode:
    image: controlnode
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      
    # Bind-mount the tutorial directory at runtime to get two-way
    # dynamic update between container and host during
    # tutorial development.
    volumes:
      - type: bind
        source: ../tutorial
        target: /tutorial
