---
# tasks file for my-example

- name: Install Ag
  apt:    
    pkg: silversearcher-ag
    state: latest
    update_cache: true


- name: Touch /etc/ssh/imposter
  file:
    path: /etc/ssh/imposter.txt
    state: touch
    mode: u=rw,g=r,o=r
